name: initial_setup
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  http: ^0.13.4
  intl: ^0.18.0
  cupertino_icons: ^1.0.0
  path_provider: ^2.0.10
  responsive_framework: ^0.2.0
  #  image and file picker
  file_picker: ^5.2.5
  image_picker: ^0.8.6
  #  Database
  sqflite: ^2.0.2+1
  shared_preferences: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

#  fonts:
#    - family: Montserrat
#      fonts:
#        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
#          weight: 200
#        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
#          weight: 800


